Repository CS3219-AY2223S1/cs3219-project-ay2223s1-g28, pull requests merged in 2022-10, with the labels that each got.

#30 Communication service implementation
  communication-service/index.js
  communication-service/package-lock.json
  communication-service/package.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/ui/chat/Chat.js
  frontend/src/components/ui/chat/ChatBlock.js
  frontend/src/components/ui/chat/ChatBlock.module.css
  frontend/src/components/ui/chat/ChatList.js
  frontend/src/components/ui/question/QuestionBox.js
  frontend/src/components/ui/question/QuestionCategories.js
  frontend/src/configs.js
  frontend/src/context/user-context.js
  frontend/src/pages/Room/index.js
  frontend/src/validators/chat-validator.js
  package-lock.json
  user-service/controller/user-controller.js
Labels: type.Enhancement, priority.High

#45 Fix overflowing code editor (Collaboration Service)
  frontend/src/pages/Room/Room.module.css
  frontend/src/pages/Room/index.js
Labels: type.Bug

#48 Comm+colab service leave session
  collaboration-service/index.js
  communication-service/index.js
  frontend/src/components/ui/collaboration/CollabEditor.js
  frontend/src/pages/Room/index.js
Labels: type.Enhancement, priority.High

#51 Communication service database
  collaboration-service/index.js
  communication-service/controller/comm-controller.js
  communication-service/index.js
  communication-service/model/chat-model.js
  communication-service/model/comm-orm.js
  communication-service/model/repository.js
  communication-service/package-lock.json
  communication-service/package.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/ui/chat/ChatBlock.js
  frontend/src/components/ui/chat/ChatList.js
  frontend/src/configs.js
  frontend/src/pages/Room/index.js
  matching-service/package-lock.json
  matching-service/package.json
Labels: type.Enhancement, priority.Medium

#60 Deployment: Frontend
  .github/workflows/frontend-cd.yml
  gke/frontend-deployment.yml
  gke/frontend-ingress.yml
  gke/frontend-service.yaml
Labels: priority.Medium

#62 Deployment: testing
  .github/workflows/frontend-cd.yml
Labels: type.Test

#65 Deployment: bug fix
  .github/workflows/frontend-cd.yml
Labels: type.Bug
