Repository CS3219-AY2223S1/cs3219-project-ay2223s1-g28, pull requests merged in 2022-11, with the labels that each got.

#50 Question service: Display same question for users in same room
  .gitignore
  frontend/src/components/ui/question/Question.js
  frontend/src/components/ui/question/QuestionBox.js
  frontend/src/components/ui/question/QuestionCategories.js
  frontend/src/components/ui/question/QuestionCategory.js
  frontend/src/components/ui/question/QuestionTitle.js
  frontend/src/configs.js
  frontend/src/pages/Match/index.js
  frontend/src/pages/Room/Room.module.css
  frontend/src/pages/Room/index.js
  matching-service/dump.rdb
  question-service/controller/question-controller.js
  question-service/index.js
  question-service/model/question-orm.js
  question-service/model/repository.js
  user-service/.dockerignore
  user-service/.env.sample
  user-service/.gitignore
  user-service/controller/user-controller.js
Labels: priority.High

#75 Bug fix: update navbar upon signout
  frontend/src/context/user-context.js
Labels: type.Bug, priority.Medium

#74 Bug fix: Show UI after successful account update
  user-service/controller/user-controller.js
  user-service/model/repository.js
  user-service/model/user-orm.js
Labels: type.Bug, priority.High

#59 Backend (Collaboration Service): Use Redis to store and load users' code
  collaboration-service/.env.sample
  collaboration-service/index.js
  collaboration-service/model/collaboration-orm.js
  collaboration-service/model/repository.js
  collaboration-service/package-lock.json
  collaboration-service/package.json
Labels: type.Enhancement, priority.Medium

#83 Development in docker: Fix backend container not running bug
  docker-compose.yml
Labels: type.Bug

#78 UI: responsive view
  frontend/src/components/forms/SigninForm.js
  frontend/src/components/forms/SigninForm.module.css
  frontend/src/components/forms/SignupForm.js
  frontend/src/components/forms/SignupForm.module.css
  frontend/src/components/forms/UpdateProfileForm.js
  frontend/src/components/forms/UpdateProfileForm.module.css
  frontend/src/components/ui/DifficultButton.module.css
  frontend/src/components/ui/DifficultyButtonGroup.js
  frontend/src/pages/Home/index.js
  frontend/src/pages/Match/index.js
  frontend/src/pages/Room/index.js
  frontend/src/pages/Signin/index.js
  frontend/src/pages/Signup/index.js
Labels: type.Enhancement, priority.Medium

#88 Deployment test
  .github/workflows/collab-cd.yaml
  .github/workflows/comm-cd.yaml
  .github/workflows/frontend-cd.yaml
  .github/workflows/gateway-cd.yaml
  .github/workflows/matching-cd.yaml
  .github/workflows/question-cd.yaml
  .github/workflows/user-cd.yaml
  gke/collab/collab-deployment.yaml
  gke/collab/collab-service.yaml
  gke/collab/kustomization.yaml
  gke/comm/comm-deployment.yaml
  gke/comm/comm-service.yaml
  gke/comm/kustomization.yaml
  gke/frontend/frontend-deployment.yaml
  gke/frontend/frontend-ingress.yaml
  gke/frontend/frontend-service.yaml
  gke/frontend/kustomization.yaml
  gke/gateway/gateway-deployment.yaml
  gke/gateway/gateway-ingress.yaml
  gke/gateway/gateway-service.yaml
  gke/gateway/kustomization.yaml
  gke/kustomization.yaml
  gke/matching/kustomization.yaml
  gke/matching/matching-deployment.yaml
  gke/matching/matching-service.yaml
  gke/question/kustomization.yaml
  gke/question/question-deployment.yaml
  gke/question/question-service.yaml
  gke/user/kustomization.yaml
  gke/user/user-deployment.yaml
  gke/user/user-service.yaml
Labels: priority.High

#92 Deployment: set up secrets and environment variables for production
  .github/workflows/collab-cd.yaml
  .github/workflows/comm-cd.yaml
  .github/workflows/frontend-cd.yaml
  .github/workflows/matching-cd.yaml
  .github/workflows/question-cd.yaml
  .github/workflows/user-cd.yaml
  collaboration-service/.env.sample
  collaboration-service/index.js
  communication-service/.env.sample
  communication-service/index.js
  frontend/src/configs.js
  gke/collab/collab-deployment.yaml
  gke/comm/comm-deployment.yaml
  gke/frontend/frontend-deployment.yaml
  gke/matching/matching-deployment.yaml
  gke/question/question-deployment.yaml
  gke/user/user-deployment.yaml
  matching-service/.env.sample
  matching-service/index.js
  question-service/.env.sample
  question-service/index.js
  user-service/.env.sample
  user-service/index.js
Labels: priority.High

#93 Deployment: delete secrets created previously
  .github/workflows/collab-cd.yaml
  .github/workflows/comm-cd.yaml
  .github/workflows/frontend-cd.yaml
  .github/workflows/matching-cd.yaml
  .github/workflows/question-cd.yaml
  .github/workflows/user-cd.yaml
Labels: priority.High

#94 Deployment: set origin for response header
  collaboration-service/index.js
  communication-service/index.js
  matching-service/index.js
Labels: priority.High

#95 Deployment: add cors origin for collaboration service
  collaboration-service/index.js
Labels: priority.High

#96 Deployment: add access control origin for NGINX header
  gateway/default.conf
Labels: priority.High

#97 Deployment: update cors
  collaboration-service/index.js
  communication-service/index.js
  matching-service/index.js
Labels: priority.High

#98 Deployment: remove extra origin and add credentials
  collaboration-service/index.js
  communication-service/index.js
  gateway/default.conf
  matching-service/index.js
Labels: priority.High

#99 Deployment: update gateway dockerfile
  gateway/Dockerfile
Labels: priority.High

#100 Deployment: correct build folder path
  .github/workflows/gateway-cd.yaml
Labels: priority.High

#101 Deployment: correct deployment name
  .github/workflows/gateway-cd.yaml
Labels: priority.High

#102 Deployment: update address for service
  gateway/default.conf
Labels: priority.High

#103 Deployment: update communication service address
  gateway/default.conf
Labels: priority.High

#104 Deployment: serve NGINX original html file
  gateway/default.conf
Labels: priority.High

#105 Deployment: remove cors for testing
  collaboration-service/index.js
  communication-service/index.js
  matching-service/index.js
Labels: priority.High

#106 Deployement: add wildcard for every service response header for testing
  gateway/default.conf
Labels: priority.High

#107 Deployment: remove double quote for env value
  gke/collab/collab-deployment.yaml
  gke/comm/comm-deployment.yaml
  gke/matching/matching-deployment.yaml
  gke/question/question-deployment.yaml
  gke/user/user-deployment.yaml
Labels: priority.High

#108 Deployment: remove custom set header for testing
  communication-service/index.js
  user-service/index.js
Labels: priority.High

#109 Deployment: delete cors and redefine request header
  gateway/default.conf
  user-service/index.js
Labels: priority.High

#110 Deployment: remove localhost for testing
  frontend/src/configs.js
Labels: priority.High

#111 Deployment: use gateway endpoint directly for testing
  frontend/src/configs.js
Labels: priority.High

#112 Deployemnt: test moving ACAO to other service
  gateway/default.conf
Labels: priority.High

#113 Deployment: add cors origin for user service
  user-service/index.js
Labels: priority.High

#114 Deployment: set header for user service response
  user-service/index.js
Labels: priority.High

#115 Deployment: add more user service response header
  user-service/index.js
Labels: priority.High

#116 Deployment: add cookie path to NGINX header
  gateway/default.conf
  user-service/index.js
Labels: priority.High

#117 Deployment: add header at nginx instead
  gateway/default.conf
  user-service/index.js
Labels: priority.High

#118 Deployment: remove extra ACAO header
  gateway/default.conf
Labels: priority.High

#119 Deployment: use old config back
  gateway/default.conf
  user-service/index.js
Labels: priority.High

#120 Deployment: set http-only cookie to strict samesite
  user-service/controller/user-controller.js
Labels: priority.High

#121 Deployment: use both allow credential true
  gateway/default.conf
  user-service/controller/user-controller.js
Labels: priority.High

#123 Deployment: set cookie domain
  gateway/default.conf
  user-service/controller/user-controller.js
Labels: priority.High

#124 Deployment: use old config
  user-service/controller/user-controller.js
Labels: priority.High

#129 Deployment: set up secure cross-domain connection
  gke/frontend/frontend-ingress.yaml
  gke/frontend/frontend-service.yaml
  gke/managed-cert.yaml
  user-service/controller/user-controller.js
Labels: priority.High

#130 Deployment: setup secure connection for gateway
  gke/gateway/gateway-ingress.yaml
  gke/gateway/gateway-service.yaml
  gke/managed-cert.yaml
Labels: priority.High

#133 Fix Bug (Matching Service): Cancel Match instead of Disconnecting
  frontend/src/pages/Match/index.js
  matching-service/controller/matching-controller.js
  matching-service/index.js
Labels: type.Bug

#135 Deploy PeerPrep onto GCP
  .github/workflows/collab-cd.yaml
  .github/workflows/comm-cd.yaml
  .github/workflows/frontend-cd.yaml
  .github/workflows/gateway-cd.yaml
  .github/workflows/matching-cd.yaml
  .github/workflows/question-cd.yaml
  .github/workflows/user-cd.yaml
  collaboration-service/.env.sample
  collaboration-service/index.js
  communication-service/.env.sample
  communication-service/index.js
  docker-compose.yml
  frontend/Dockerfile
  frontend/src/components/ui/chat/ChatList.js
  frontend/src/configs.js
  gateway/Dockerfile
  gateway/default.conf
  gke/collab/collab-deployment.yaml
  gke/collab/collab-service.yaml
  gke/collab/kustomization.yaml
  gke/comm/comm-deployment.yaml
  gke/comm/comm-service.yaml
  gke/comm/kustomization.yaml
  gke/frontend/frontend-deployment.yaml
  gke/frontend/frontend-ingress.yaml
  gke/frontend/frontend-service.yaml
  gke/frontend/kustomization.yaml
  gke/gateway/gateway-deployment.yaml
  gke/gateway/gateway-ingress.yaml
  gke/gateway/gateway-service.yaml
  gke/gateway/kustomization.yaml
  gke/kustomization.yaml
  gke/managed-cert.yaml
  gke/matching/kustomization.yaml
  gke/matching/matching-deployment.yaml
  gke/matching/matching-service.yaml
  gke/question/kustomization.yaml
  gke/question/question-deployment.yaml
  gke/question/question-service.yaml
  gke/user/kustomization.yaml
  gke/user/user-deployment.yaml
  gke/user/user-service.yaml
  matching-service/.env.sample
  matching-service/index.js
  question-service/.env.sample
  question-service/index.js
  user-service/.env.sample
  user-service/controller/user-controller.js
  user-service/index.js
Labels: priority.High

#157 Add Readme
  README.md
Labels: priority.High

#158 Fix README typo
  README.md
Labels: type.Documentation, priority.High
